"""Add workflow_comments table

Revision ID: 87fbb6a534f4
Revises: af78095d1436
Create Date: 2025-10-31 03:11:04.720243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87fbb6a534f4'
down_revision: Union[str, Sequence[str], None] = 'af78095d1436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workflow_comments_user_id_users')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_comments_workflow_id_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_comments'))
    )
    op.create_index(op.f('ix_workflow_comments_id'), 'workflow_comments', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_comments_user_id'), 'workflow_comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_workflow_comments_workflow_id'), 'workflow_comments', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_comments_workflow_id'), table_name='workflow_comments')
    op.drop_index(op.f('ix_workflow_comments_user_id'), table_name='workflow_comments')
    op.drop_index(op.f('ix_workflow_comments_id'), table_name='workflow_comments')
    op.drop_table('workflow_comments')
    # ### end Alembic commands ###
