"""add all excel columns to asset model

Revision ID: ac73feb093d2
Revises: a95dd87146e9
Create Date: 2025-10-30 23:45:35.715671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac73feb093d2'
down_revision: Union[str, Sequence[str], None] = 'a95dd87146e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('purchase_request', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('tax_invoice_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assets', sa.Column('furniture_category', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('detailed_category', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('checkout_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assets', sa.Column('return_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assets', sa.Column('previous_user_1', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('previous_user_2', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('first_user', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('old_asset_number', sa.String(length=50), nullable=True))
    op.add_column('assets', sa.Column('qr_code_exists', sa.String(length=10), nullable=True))
    op.add_column('assets', sa.Column('special_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'special_notes')
    op.drop_column('assets', 'qr_code_exists')
    op.drop_column('assets', 'old_asset_number')
    op.drop_column('assets', 'first_user')
    op.drop_column('assets', 'previous_user_2')
    op.drop_column('assets', 'previous_user_1')
    op.drop_column('assets', 'return_date')
    op.drop_column('assets', 'checkout_date')
    op.drop_column('assets', 'detailed_category')
    op.drop_column('assets', 'furniture_category')
    op.drop_column('assets', 'tax_invoice_date')
    op.drop_column('assets', 'purchase_request')
    # ### end Alembic commands ###
