"""remove_name_field_from_assets

Revision ID: af78095d1436
Revises: a0bcc264bdb9
Create Date: 2025-10-31 01:17:16.463862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af78095d1436'
down_revision: Union[str, Sequence[str], None] = 'a0bcc264bdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_history_action'), table_name='asset_history')
    op.drop_index(op.f('idx_history_asset'), table_name='asset_history')
    op.drop_index(op.f('idx_history_asset_date'), table_name='asset_history')
    op.drop_index(op.f('idx_history_created_at'), table_name='asset_history')
    op.drop_index(op.f('idx_assets_assigned_to'), table_name='assets')
    op.drop_index(op.f('idx_assets_category'), table_name='assets')
    op.drop_index(op.f('idx_assets_deleted'), table_name='assets', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('idx_assets_location'), table_name='assets')
    op.drop_index(op.f('idx_assets_search'), table_name='assets')
    op.drop_index(op.f('idx_assets_serial'), table_name='assets')
    op.drop_index(op.f('idx_assets_status'), table_name='assets')
    op.drop_index(op.f('idx_assets_tag'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_column('assets', 'name')
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_workflows_asset'), table_name='workflows')
    op.drop_index(op.f('idx_workflows_created'), table_name='workflows')
    op.drop_index(op.f('idx_workflows_requester'), table_name='workflows')
    op.drop_index(op.f('idx_workflows_status'), table_name='workflows')
    op.drop_index(op.f('idx_workflows_type'), table_name='workflows')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_workflows_type'), 'workflows', ['type'], unique=False)
    op.create_index(op.f('idx_workflows_status'), 'workflows', ['status'], unique=False)
    op.create_index(op.f('idx_workflows_requester'), 'workflows', ['requester_id'], unique=False)
    op.create_index(op.f('idx_workflows_created'), 'workflows', ['created_at'], unique=False)
    op.create_index(op.f('idx_workflows_asset'), 'workflows', ['asset_id'], unique=False)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.add_column('assets', sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('idx_assets_tag'), 'assets', ['asset_tag'], unique=False)
    op.create_index(op.f('idx_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('idx_assets_serial'), 'assets', ['serial_number'], unique=False)
    op.create_index(op.f('idx_assets_search'), 'assets', ['category_id', 'status', 'assigned_to'], unique=False)
    op.create_index(op.f('idx_assets_location'), 'assets', ['location_id'], unique=False)
    op.create_index(op.f('idx_assets_deleted'), 'assets', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_assets_category'), 'assets', ['category_id'], unique=False)
    op.create_index(op.f('idx_assets_assigned_to'), 'assets', ['assigned_to'], unique=False)
    op.create_index(op.f('idx_history_created_at'), 'asset_history', ['created_at'], unique=False)
    op.create_index(op.f('idx_history_asset_date'), 'asset_history', ['asset_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_history_asset'), 'asset_history', ['asset_id'], unique=False)
    op.create_index(op.f('idx_history_action'), 'asset_history', ['action'], unique=False)
    # ### end Alembic commands ###
