"""remove_manufacturer_and_warranty_end

Revision ID: a0bcc264bdb9
Revises: b93df68d127d
Create Date: 2025-10-31 00:36:46.476823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0bcc264bdb9'
down_revision: Union[str, Sequence[str], None] = 'b93df68d127d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Preserve critical indexes - commenting out drops
    # op.drop_index(op.f('idx_history_action'), table_name='asset_history')
    # op.drop_index(op.f('idx_history_asset'), table_name='asset_history')
    # op.drop_index(op.f('idx_history_asset_date'), table_name='asset_history')
    # op.drop_index(op.f('idx_history_created_at'), table_name='asset_history')
    # op.drop_index(op.f('idx_assets_assigned_to'), table_name='assets')
    # op.drop_index(op.f('idx_assets_category'), table_name='assets')
    # op.drop_index(op.f('idx_assets_deleted'), table_name='assets', postgresql_where='(deleted_at IS NULL)')
    # op.drop_index(op.f('idx_assets_location'), table_name='assets')
    # op.drop_index(op.f('idx_assets_search'), table_name='assets')
    # op.drop_index(op.f('idx_assets_serial'), table_name='assets')
    # op.drop_index(op.f('idx_assets_status'), table_name='assets')
    # op.drop_index(op.f('idx_assets_tag'), table_name='assets')

    # Remove columns that don't exist in Excel
    op.drop_column('assets', 'warranty_end')
    op.drop_column('assets', 'manufacturer')

    # Preserve sort_order default
    # op.alter_column('categories', 'sort_order',
    #            existing_type=sa.INTEGER(),
    #            server_default=None,
    #            existing_nullable=False)

    # Preserve workflow indexes
    # op.drop_index(op.f('idx_workflows_asset'), table_name='workflows')
    # op.drop_index(op.f('idx_workflows_created'), table_name='workflows')
    # op.drop_index(op.f('idx_workflows_requester'), table_name='workflows')
    # op.drop_index(op.f('idx_workflows_status'), table_name='workflows')
    # op.drop_index(op.f('idx_workflows_type'), table_name='workflows')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Note: Index recreations commented out since we preserved them in upgrade
    # op.create_index(op.f('idx_workflows_type'), 'workflows', ['type'], unique=False)
    # op.create_index(op.f('idx_workflows_status'), 'workflows', ['status'], unique=False)
    # op.create_index(op.f('idx_workflows_requester'), 'workflows', ['requester_id'], unique=False)
    # op.create_index(op.f('idx_workflows_created'), 'workflows', ['created_at'], unique=False)
    # op.create_index(op.f('idx_workflows_asset'), 'workflows', ['asset_id'], unique=False)

    # Restore sort_order default (kept commented since we preserved it)
    # op.alter_column('categories', 'sort_order',
    #            existing_type=sa.INTEGER(),
    #            server_default=sa.text('0'),
    #            existing_nullable=False)

    # Restore removed columns
    op.add_column('assets', sa.Column('manufacturer', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('warranty_end', sa.DATE(), autoincrement=False, nullable=True))

    # Note: Index recreations commented out since we preserved them in upgrade
    # op.create_index(op.f('idx_assets_tag'), 'assets', ['asset_tag'], unique=False)
    # op.create_index(op.f('idx_assets_status'), 'assets', ['status'], unique=False)
    # op.create_index(op.f('idx_assets_serial'), 'assets', ['serial_number'], unique=False)
    # op.create_index(op.f('idx_assets_search'), 'assets', ['category_id', 'status', 'assigned_to'], unique=False)
    # op.create_index(op.f('idx_assets_location'), 'assets', ['location_id'], unique=False)
    # op.create_index(op.f('idx_assets_deleted'), 'assets', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NULL)')
    # op.create_index(op.f('idx_assets_category'), 'assets', ['category_id'], unique=False)
    # op.create_index(op.f('idx_assets_assigned_to'), 'assets', ['assigned_to'], unique=False)
    # op.create_index(op.f('idx_history_created_at'), 'asset_history', ['created_at'], unique=False)
    # op.create_index(op.f('idx_history_asset_date'), 'asset_history', ['asset_id', 'created_at'], unique=False)
    # op.create_index(op.f('idx_history_asset'), 'asset_history', ['asset_id'], unique=False)
    # op.create_index(op.f('idx_history_action'), 'asset_history', ['action'], unique=False)
    # ### end Alembic commands ###
