"""update asset status enum with actual values

Revision ID: a95dd87146e9
Revises: 97b54c3e6d34
Create Date: 2025-10-30 23:29:02.263698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95dd87146e9'
down_revision: Union[str, Sequence[str], None] = '97b54c3e6d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_assets_asset_tag'), table_name='assets')
    op.drop_index(op.f('idx_assets_assigned_to'), table_name='assets')
    op.drop_index(op.f('idx_assets_category_id'), table_name='assets')
    op.drop_index(op.f('idx_assets_deleted_status'), table_name='assets')
    op.drop_index(op.f('idx_assets_grade'), table_name='assets')
    op.drop_index(op.f('idx_assets_location_id'), table_name='assets')
    op.drop_index(op.f('idx_assets_model'), table_name='assets')
    op.drop_index(op.f('idx_assets_name'), table_name='assets')
    op.drop_index(op.f('idx_assets_serial_number'), table_name='assets')
    op.drop_index(op.f('idx_assets_status'), table_name='assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('idx_assets_serial_number'), 'assets', ['serial_number'], unique=False)
    op.create_index(op.f('idx_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('idx_assets_model'), 'assets', ['model'], unique=False)
    op.create_index(op.f('idx_assets_location_id'), 'assets', ['location_id'], unique=False)
    op.create_index(op.f('idx_assets_grade'), 'assets', ['grade'], unique=False)
    op.create_index(op.f('idx_assets_deleted_status'), 'assets', ['deleted_at', 'status'], unique=False)
    op.create_index(op.f('idx_assets_category_id'), 'assets', ['category_id'], unique=False)
    op.create_index(op.f('idx_assets_assigned_to'), 'assets', ['assigned_to'], unique=False)
    op.create_index(op.f('idx_assets_asset_tag'), 'assets', ['asset_tag'], unique=False)
    # ### end Alembic commands ###
